name: home
description: Home Example
version: 1.0.0

environment:  
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  json_annotation: ^4.7.0
  http: ^0.13.5
  rxdart: ^0.27.7
  chassis_core:
    path: ../../../chassis
  chassis_annotation:
    path: ../../../annotation/

dev_dependencies:
  build_runner: ^2.3.3
  chassis_generator:
    path: ../../../generator
  json_serializable: ^6.5.4
  test: ^1.0.0