name: chassis_generator
description: Generator for Chassis Providers
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  build: 
  analyzer: ^5.4.0
  source_gen: ^1.2.6
  code_builder: ^4.4.0
  chassis_annotation:
    path: ../annotation/
  reflectable: ^4.0.4

dev_dependencies:
  build_runner: ^2.3.3
  build_test:
  test: ^1.0.0
