import 'dart:async';

import '../../model/model.dart';

/// A base class for data resolver.
/// Version 2.0
/// Generated by Chassis Back-end.
abstract class DataResolverBase {
  Map<String, DataResolverBase> routeTable = {};

  bool getData(
      StreamController<Map<String, dynamic>> controller, Request request) {
    final stream = resolveWith(request);
    if (stream != null) {
      controller.addStream(stream.map((event) => event.toJson()));
      return true;
    }
    return false;
  }

  Stream<Output>? resolveWith(Request request) {
    print('No resolver found');
    return null;
  }
}
