import 'package:chassis_core/core.dart';

// Generated by Chassis Back-end
class BannerInput extends Input {
  String slug;

  @override
  String? get resolver => "get-banner";

  BannerInput({required this.slug});

  factory BannerInput.fromJson(Map<String, dynamic> json) =>
      BannerInput(slug: json['slug']);

  factory BannerInput.fromRequest(Request request) =>
      BannerInput.fromJson(request.input ?? {});
}
