import 'package:chassis_core/core.dart';

/// Generated by Chassis Back-end
class BannerOutput extends Output {
  String? asset;
  String? placeholder;

  @override
  Map<String, dynamic> toJson() {
    return {'asset': asset, 'placeholder': placeholder};
  }

  BannerOutput({this.asset, this.placeholder});
}
