name: chassis_core
description: Core of Chassis Library
version: 1.0.0

environment:  
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  chassis_annotation:
    path: ../annotation/
  rxdart: ^0.27.7
  
dev_dependencies:
  test: ^1.0.0