import 'dart:async';

import 'package:chassis_core/core.dart';
import 'package:chassis_annotation/annotation.dart';

import '../../model/banner_input.dart';
import '../../model/banner_output.dart';

part 'data_resolver.part.dart';

///  Generated by Chassis Back-end
abstract class DataResolver extends DataResolverBase with DataResolverEntry {
  @override
  Stream<Output>? resolveWith(Request request) {
    final resolver = request.resolvedWith;
    switch (resolver) {
      case "get-banner":
        return getBanner(BannerInput.fromRequest(request));
      case "get-banner-v2":
        return getBannerV2(BannerInput.fromRequest(request));
      default:
        return super.resolveWith(request);
    }
  }
}
