part of 'data_resolver.dart';

///  Generated by Chassis Back-end
abstract class DataResolverEntry {
  @Resolves(resolvedWith: "get-banner")
  Stream<BannerOutput>? getBanner(BannerInput input) => null;

  @Resolves(resolvedWith: "get-banner-v2")
  Stream<BannerOutput>? getBannerV2(BannerInput input) => null;
}
